/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

const ParkChair = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf'
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.chair.geometry}
        material={materials['BrownDark.052']}
      />
    </group>
  );
};

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf'
);

export default ParkChair;
