/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

const Skunk = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/skunk/model.gltf'
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh
        geometry={nodes.Cube003.geometry}
        material={materials['1']}
        skeleton={nodes.Cube003.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube003_1.geometry}
        material={materials['2']}
        skeleton={nodes.Cube003_1.skeleton}
      />
    </group>
  );
};

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/skunk/model.gltf'
);

export default Skunk;
